name: Pull Request Analysis

on:
  pull_request:
    branches:
      - '*'

jobs:
  analyze_code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Realizar análisis de SAST
      run: echo "Realizando análisis de SAST"

    - name: Comprobar requisitos
      id: check_requirements
      run: |
        if [ -f "allow_pull_request.txt" ]; then
          echo "Permitiendo Pull Request"
          echo "allow_pull=true" >> $GITHUB_ENV
        else
          echo "Impidiendo Pull Request"
          echo "allow_pull=false" >> $GITHUB_ENV
          exit 1
        fi

    - name: Permitir la build si allow_pull es True
      if: steps.check_requirements.outputs.allow_pull == 'true'
      run: echo "Permitiendo Pull Request"

    - name: Impedir la build si allow_pull es False
      if: steps.check_requirements.outputs.allow_pull == 'false'
      run: |
        echo "Build fallida. Impidiendo Pull Request"
        exit 1

    - name: Guardar archivo como artefacto
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: allow_pull_request
        path: allow_pull_request.txt
